### ISSUE TITLE
Detalle grabación

### ISSUE THREAD

**Issue by jgo0038** [gpm0009/GESPRO_PracticaGestionTareas_1718#91]
![image](https://user-images.githubusercontent.com/33413667/32889221-4c69c0ec-caca-11e7-8271-04c28c2d1032.png)

**Comment by RaquelSancha** [comment]
Bien hecho

**Comment by gpm0009** [comment]
Genial compi ^^

**Comment by ZoeCalvo** [comment]
Buen trabajo, aunque creo que te debería haber llevado menos tiempo.
